-- --------------------------------------------------------------------------
-- Table gift_certificate
-- --------------------------------------------------------------------------
create TABLE IF NOT EXISTS gift_certificate(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                character varying(30),
    description         character varying(200),
    price               DECIMAL(5, 2),
    duration            integer,
    create_date         timestamp without time zone,
    last_update_date    timestamp without time zone
);

-- --------------------------------------------------------------------------
-- Table tag
-- --------------------------------------------------------------------------
create TABLE IF NOT EXISTS tag(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                character varying
);

-- --------------------------------------------------------------------------
-- Table gift_certificate_tags
-- --------------------------------------------------------------------------
create TABLE IF NOT EXISTS gift_certificate_tag(
    gift_certificate_id   bigint REFERENCES gift_certificate (id),
    tag_id                bigint REFERENCES tag (id),
    PRIMARY KEY (gift_certificate_id, tag_id)
);

-- --------------------------------------------------------------------------
-- Table customer
-- --------------------------------------------------------------------------
create TABLE IF NOT EXISTS customer(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                character varying
);

-- --------------------------------------------------------------------------
-- Table customerOrder
-- --------------------------------------------------------------------------
create TABLE IF NOT EXISTS customer_order(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         bigint,
    purchase_time       timestamp without time zone,
    amount              DECIMAL(5, 2)
);

-- --------------------------------------------------------------------------
-- Table order_gift_certificates
-- --------------------------------------------------------------------------
create TABLE IF NOT EXISTS customer_order_gift_certificate(
    customer_order_id     bigint REFERENCES customer_order (id),
    gift_certificate_id   bigint REFERENCES gift_certificate (id),
    PRIMARY KEY (customer_order_id, gift_certificate_id)
);

commit;
